
-- Create a table for tracking user activity
create table if not exists public.user_activity_logs (
  id bigint generated by default as identity primary key,
  user_id text,
  user_email text,
  action_type text not null,
  details jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Optional, but good practice)
alter table public.user_activity_logs enable row level security;

-- Allow anyone (anon) to insert logs for now (since we log guest actions too)
create policy "Allow public insert to logs"
  on public.user_activity_logs for insert
  with check (true);

-- Allow authenticated users to view their own logs
create policy "Users can view own logs"
  on public.user_activity_logs for select
  using (auth.uid()::text = user_id);
