-- 1. Create the products table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  category text not null,
  image text not null,
  description text not null,
  tags text[] not null,
  rating numeric default 0,
  reviews numeric default 0
);

-- 2. Insert sample data (taken from your constants.ts)
insert into public.products 
(name, price, category, image, description, tags, rating, reviews)
values
  ('Minimalist Wool Coat', 189.99, 'Outerwear', 'https://picsum.photos/seed/coat1/600/800', 'Wrap yourself in sophisticated warmth with this timeless wool coat.', ARRAY['winter', 'formal', 'coat', 'wool'], 4.8, 128),
  ('Silk Evening Dress', 249.50, 'Dresses', 'https://picsum.photos/seed/dress2/600/800', 'Exude ethereal grace in this flowing silk evening dress.', ARRAY['evening', 'summer', 'luxury', 'silk'], 4.9, 84),
  ('Urban Denim Jacket', 89.00, 'Jackets', 'https://picsum.photos/seed/jacket3/600/800', 'Redefine urban edge with this modern denim jacket.', ARRAY['casual', 'streetwear', 'denim'], 4.6, 215),
  ('Cashmere Turtleneck', 120.00, 'Knitwear', 'https://picsum.photos/seed/sweater4/600/800', 'Indulge in the cloud-like embrace of pure cashmere.', ARRAY['winter', 'cozy', 'casual'], 4.9, 62),
  ('Tailored Linen Trousers', 95.00, 'Bottoms', 'https://picsum.photos/seed/pant5/600/800', 'Experience the breezy freedom of these tailored linen trousers.', ARRAY['summer', 'formal', 'office', 'breathable'], 4.5, 94),
  ('Leather Chelsea Boots', 155.00, 'Footwear', 'https://picsum.photos/seed/boot6/600/800', 'Step with confidence in these handcrafted leather Chelsea boots.', ARRAY['shoes', 'leather', 'winter', 'casual'], 4.7, 156),
  ('Oversized Cotton Shirt', 65.00, 'Tops', 'https://picsum.photos/seed/shirt7/600/800', 'Capture the essence of effortless chic with this oversized cotton shirt.', ARRAY['casual', 'summer', 'basics'], 4.4, 302),
  ('Bohemian Maxi Skirt', 78.00, 'Bottoms', 'https://picsum.photos/seed/skirt8/600/800', 'Embrace bohemian whimsy with this vibrant maxi skirt.', ARRAY['summer', 'boho', 'casual'], 4.8, 110);
